In [ ]:
#Create a NumPy array with the following values: [1, 2, 3, 4, 5].

In [10]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])


In [11]:
#Print the shape of the array using the .shape attribute.

In [12]:
print(array.shape[0])

5


In [13]:
#Reshape the array into a 2D array with 2 rows and 3 columns

In [14]:
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape(2, 3)

print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Print the shape of the new array.

In [19]:
print(reshaped_array.shape)

(2, 3)


In [20]:
#Create a second NumPy array with the following values: [6, 7, 8, 9, 10].

In [21]:
second_array = np.array([6, 7, 8, 9, 10])

In [22]:
second_array

array([ 6,  7,  8,  9, 10])

In [24]:
#Concatenate the two arrays together horizontally.

In [26]:
concatenated_array = np.hstack((array, second_array))



In [27]:
#Print the resulting array.

In [28]:
print(concatenated_array)

[ 1  2  3  4  5  6  6  7  8  9 10]


In [30]:
#Compute the resulting array's mean, median, and standard deviation.

In [31]:
mean = np.mean(concatenated_array)
median = np.median(concatenated_array)
standard_deviation = np.std(concatenated_array)

print("Mean:", mean)
print("Median:", median)
print("Standard deviation:", standard_deviation)

Mean: 5.545454545454546
Median: 6.0
Standard deviation: 2.74238238709061
